[34m[1mwandb[39m[22m: logging graph, to disable use `wandb.watch(log_graph=False)`
/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/lightning_fabric/connector.py:563: `precision=16` is supported for historical reasons but its usage is discouraged. Please set your precision to 16-mixed instead!
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/noah00001/Desktop/projects/OrCo/OrCo_src/solo_learn/main_pretrain.py", line 255, in main
    trainer.fit(model, train_loader, val_loader, ckpt_path=ckpt_path)
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
                                       ^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/noah00001/Desktop/projects/OrCo/OrCo_src/solo_learn/solo/data/fscil_dataloader/miniimagenet/miniimagenet.py", line 107, in __getitem__
    image = self.transform(Image.open(path).convert('RGB'))
                           ^^^^^^^^^^^^^^^^
  File "/home/noah00001/anaconda3/envs/fscil_env/lib/python3.12/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/noah00001/Desktop/dataset/miniimagenet/images/n0153282900000007.jpg'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Sanity Checking: |                                                                                                                                                                                                                                                             | 0/? [00:00<?, ?it/s]